create table lx(
 lx_id               int unsigned         NOT NULL PRIMARY KEY AUTO_INCREMENT,
 ch_name             varchar(20)          DEFAULT ' ',
 used_name           varchar(20)          DEFAULT ' ',
 py_name             varchar(50)          DEFAULT ' ',
 sex                 varchar(5)           DEFAULT ' ',
 ethnicity           varchar(10)          DEFAULT ' ',
 passport_no	     varchar(10)	  DEFAULT ' ', 
 date_expriy         date                 not null ,
 date_birth          date                 not null ,
 id_num              varchar(20)          DEFAULT ' ', 
 o_tel               varchar(20)          DEFAULT ' ',
 cn_tel              varchar(20)          DEFAULT ' ',
 cn_te2              varchar(20)          DEFAULT ' ',
 wechat              varchar(20)          DEFAULT ' ',
 mail                varchar(50)          DEFAULT ' ',
 qq_num              varchar(20)          DEFAULT ' ',
 native_place        varchar(50)          DEFAULT ' ',
 nationality         varchar(50)          DEFAULT ' ',
 residence           varchar(50)          DEFAULT ' ',
 cn_residence        varchar(50)          DEFAULT ' ',
 present_industry    varchar(50)          DEFAULT ' ',
 com_name            varchar(50)          DEFAULT ' ', 
 position            varchar(50)          DEFAULT ' ',
 education           varchar(20)          DEFAULT ' ',
 health              varchar(20)          DEFAULT ' ',
 registrant          varchar(20)          DEFAULT ' ',
 photo               varchar(100)         DEFAULT ' ',
 reg_date            date                 not null ,
 remarks             varchar(100)         DEFAULT ' ',
 en_cname            varchar(100)         DEFAULT ' ',
 ch_cname            varchar(100)         DEFAULT ' ',
 degree              varchar(50)          DEFAULT ' ',
 gra_date            date                 not null ,
 del                 varchar(5)           DEFAULT ' '
)